### PR TITLE
Jurassic Journalists

### PR DESCRIPTION
**Pull request by HypoT**
initial commit for pull

### CODE REVIEW

**Comment by lemonsaurus** [comment]
Failing lint:
```
./jurassic-journalists/main.py:16:1: F401 'kivy.graphics.Canvas' imported but unused
./jurassic-journalists/main.py:54:5: E301 expected 1 blank line, found 0
./jurassic-journalists/main.py:101:5: E301 expected 1 blank line, found 0
./jurassic-journalists/main.py:167:41: E231 missing whitespace after ','
./jurassic-journalists/main.py:186:13: E128 continuation line under-indented for visual indent
./jurassic-journalists/main.py:195:101: E501 line too long (104 > 100 characters)
./jurassic-journalists/classes.py:2:1: E302 expected 2 blank lines, found 0
./jurassic-journalists/classes.py:4:22: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:27: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:32: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:37: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:43: E251 unexpected spaces around keyword / parameter equals
./jurassic-journalists/classes.py:4:45: E251 unexpected spaces around keyword / parameter equals
./jurassic-journalists/classes.py:4:50: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:54: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:58: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:63: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:71: E231 missing whitespace after ','
./jurassic-journalists/classes.py:4:79: E231 missing whitespace after ','
```

Merge conflict with `.gitignore`

**Comment by MrGrote** [comment]
Most of the python code resides inside of a single file. This would benefit from being split over multiple files.
The class Letter does have it's own file but the file is called classes.py, which is non descriptive of it's contents.
Some code has been left behind in comments, this should really be removed before you commit your code.
The code could benefit from the more consistent use of docstrings.

**Comment by HypoT** [comment]
Appreciate the review.

To explain some of the cons, had to git on mobile at the start of the week so thats where the .kivy inclusion and most probably the file endings came from (I'll need to have a look there). And must have forgot to run flake over the last commit or 2.

On the improvements - wasn't thinking of too much that I could add to the paper, for the typewriter I did want to have the roller move horizonally with the paper and yea make the wheel functional (spent too much time cutting out those keys though). Might look at salts bounce animation for a scatter'd paper though if I can get a scatter here somewhat realisic looking.

Regarding bugs, the sticking buttons, yea was aware that I could correct my watching/acting on the animations but seemed better to make it a feature & have it unstick itself, though meant to have it not type while stuck.

The eraser, yea is bugged - in terms of where the gesture gets translated to, not used fb before so was stabbing in the dark with little time there. 

Actual bug, there is another WIP phone interface [ hidden button main screen top right ] there thats registering 1 click as two, was working correctly when initially made. Need to track down how that got introduced.  The auto-text was going to be part of a slimmed down version of what I wanted with serveral objects with varying degrees of interaction; where while typewriter would type & the phone would appear, running a playable snake/pong. Couple factors stopped much being done in that direction, didn't even notice the bug until after.

Regarding 'kv rules duplicated in files (redundant) because the unused "jurassicjournalist.kv" file wasn't removed.', not sure I'm following - that file remains used as far as I'm aware, and there was some duplication, i.e. raising  re-declaration warnings in earlier commits, but they were corrected; unless I'm looking at different files.

Can blame time / poor management for the rest (lack of docstrings etc). Got round to splitting the initial single kv, and moving stuff to assets but not to combining and resplitting the py into parts.

**Comment by aeros** [comment]
@HypoT 
> Can blame time / poor management for the rest (lack of docstrings etc).

As a general suggestion, I'd advise writing the docstrings *before* writing the actual code for the class, method, or function. Of course, it should be updated as needed, but in general this can help a lot to improve both the quality and scope. It can also improve your coding efficiency, as you can simply reference your own docstrings if you have to take a break and come back, or if you lose your train of thought.

Otherwise, you'll often find that documentation is just something that you never have time for (this also applies to unit tests); it's a common real-world issue.

**Comment by tshirtman** [comment]
> On the improvements - wasn't thinking of too much that I could add to the paper, for the typewriter I did want to have the roller move horizonally with the paper and yea make the wheel functional (spent too much time cutting out those keys though). Might look at salts bounce animation for a scatter'd paper though if I can get a scatter here somewhat realisic looking.

Sure, time was limited, it would indeed have been nice to have the roller move with the paper, i didn't even realize that was off, but no big deal, time is indeed limited, and i would have been really impressed if you had implemented all the things i suggested).

> Actual bug, there is another WIP phone interface [ hidden button main screen top right ] there thats registering 1 click as two, was working correctly when initially made. Need to track down how that got introduced. The auto-text was going to be part of a slimmed down version of what I wanted with serveral objects with varying degrees of interaction; where while typewriter would type & the phone would appear, running a playable snake/pong. Couple factors stopped much being done in that direction, didn't even notice the bug until after.

Yes i discovered the button using the inspector, as i didn't understand what the code for it was there for, so i looked where that was in the actual interface to use it, did you want to implement T9 text input?

> Regarding 'kv rules duplicated in files (redundant) because the unused "jurassicjournalist.kv" file wasn't removed.', not sure I'm following - that file remains used as far as I'm aware, and there was some duplication, i.e. raising re-declaration warnings in earlier commits, but they were corrected; unless I'm looking at different files.

Ok, the file looked duplicated, and as you load/return your own kv files, i assumed that automatic load wasn't really used anymore, i didn't test this assumption by deleting it though, i assumed it was just not causing any issue to have it, i'll edit my review.

**Comment by HypoT** [comment]
> Yes i discovered the button using the inspector, as i didn't understand what the code for it was there for, so i looked where that was in the actual interface to use it, did you want to implement T9 text input

Indeed - both inputs are in the apk (which I should've left up) - coded those to give a console for someone else to utilise in any way they saw fit, but didnt make much headway there.

The T9 in the apk works fine, without the double character issue. Barring quad tap - which I was going to add in with a long press.

**Pull request merged**
